// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api/user_v1/service_grpc.proto

package user_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendMessageToTelegramClient is the client API for SendMessageToTelegram service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendMessageToTelegramClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type sendMessageToTelegramClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMessageToTelegramClient(cc grpc.ClientConnInterface) SendMessageToTelegramClient {
	return &sendMessageToTelegramClient{cc}
}

func (c *sendMessageToTelegramClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/user_v1.SendMessageToTelegram/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMessageToTelegramServer is the server API for SendMessageToTelegram service.
// All implementations must embed UnimplementedSendMessageToTelegramServer
// for forward compatibility
type SendMessageToTelegramServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedSendMessageToTelegramServer()
}

// UnimplementedSendMessageToTelegramServer must be embedded to have forward compatible implementations.
type UnimplementedSendMessageToTelegramServer struct {
}

func (UnimplementedSendMessageToTelegramServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSendMessageToTelegramServer) mustEmbedUnimplementedSendMessageToTelegramServer() {}

// UnsafeSendMessageToTelegramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendMessageToTelegramServer will
// result in compilation errors.
type UnsafeSendMessageToTelegramServer interface {
	mustEmbedUnimplementedSendMessageToTelegramServer()
}

func RegisterSendMessageToTelegramServer(s grpc.ServiceRegistrar, srv SendMessageToTelegramServer) {
	s.RegisterService(&SendMessageToTelegram_ServiceDesc, srv)
}

func _SendMessageToTelegram_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageToTelegramServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_v1.SendMessageToTelegram/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageToTelegramServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendMessageToTelegram_ServiceDesc is the grpc.ServiceDesc for SendMessageToTelegram service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendMessageToTelegram_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_v1.SendMessageToTelegram",
	HandlerType: (*SendMessageToTelegramServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SendMessageToTelegram_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user_v1/service_grpc.proto",
}
